#ifndef PPU_DEFINES_H
#define PPU_DEFINES_H

#define PPU_CTRL_ADDR 0x2000
#define PPU_CTRL_FLAG_NAMETABLE_ADDR_2000 0
#define PPU_CTRL_FLAG_NAMETABLE_ADDR_2400 1
#define PPU_CTRL_FLAG_NAMETABLE_ADDR_2800 2
#define PPU_CTRL_FLAG_NAMETABLE_ADDR_2C00 3
#define PPU_CTRL_FLAG_SPRITE_PTRN_ADDR (1<<3)
#define PPU_CTRL_FLAG_BG_PTRN_ADDR (1<<4)
#define PPU_CTRL_FLAG_SPRITE_SIZE (1<<5)
#define PPU_CTRL_FLAG_MASTER_SELECT (1<<6)
#define PPU_CTRL_FLAG_GEN_NMI (1<<7)

#define PPU_MASK_ADDR 0x2001
#define PPU_MASK_FLAG_GRAYSCALE (1)
#define PPU_MASK_FLAG_SHOW_LEFTMOST_BG (1<<1)
#define PPU_MASK_FLAG_SHOW_LEFTMOST_SPRITES (1<<2)
#define PPU_MASK_FLAG_SHOW_BG (1<<3
#define PPU_MASK_FLAG_SHOW_SPRITES (1<<4)
#define PPU_MASK_FLAG_INTENSIFY_REDS (1<<5)
#define PPU_MASK_FLAG_INTENSIFY_GREENS (1<<6)
#define PPU_MASK_FLAG_INTENSIFY_BLUES (1<<7)

#define PPU_FLAG_ADD_TO_X_SCROLL 1
#define PPU_FLAG_ADD_TO_Y_SCROLL 2

#define PPU_SCROLL_X_AMMOUNT 256
#define PPU_SCROLL_Y_AMMOUNT 240

#define PPU_VRAM_SIZE 0x3FFF
#define PPU_FLAG_BANK_1000 0x1

#define PPU_FLAG_FLIP_HORIZONTAL (1<<6)
#define PPU_FLAG_FLIP_VERTICAL (1<<7)

#define PPU_OAM_NUM_SPRITES 64
#define PPU_OAM_NUM_BYTES 4

#endif
